---
title: "Analysis of GWAS Catalog data for 'Intro to R' workshop"
author: Peter Carbonetto
date: February 7, 2017
output: html_document
---

## Overview

This is an *R Markdown Notebook*.
[R Markdown](http://r4ds.had.co.nz/r-markdown.html) combines
[Markdown](http://daringfireball.net/projects/markdown), a popular,
easy-to-read plain text formatting syntax, with "chunks" of R
code. *Explain here what is neat about notebooks.*

This notebook contains code to reproduce some of my analyses of the
GWAS Catalog data. *Add a few more sentences here about the GWAS
Catalog data, and why we might want to analyze it.*

For more background, read the [GWAS Catalog
paper](http://doi.org/10.1093/nar/gkt1229). See also the [GWAS
Diagram](http://www.ebi.ac.uk/gwas/diagram) for an evocative visual
summary of the data.

Give overview of the steps in our analysis (as a list): retrieve code
and data, set up R environment, etc.

## Introduce yourself

Introduce yourself to your neighbors. If you get stuck, please ask one your 
peers for help before asking the instructor. Conversely, if you have completed
the steps more quickly than others, consider helping your neighbors.

## Setting up your R programming environment

There are several options for setting up your R programming environment. 
In this section, we will explore the R environment options that are 
available on the *midway* compute cluster, and on your laptop (or personal 
computer). 

### R on your computer

There are 

### R on midway, no graphics

### R on midway, with graphics

First, we will



Choose: RStudio or R + editor (e.g., emacs).

Often called the *working environment*.

## Downloading the code

*Instructions on cloning or downloading the github repository go
here. You should have a folder somewhere on your computer, or in your
home folder on a compute cluster, called `R-intro`.*

Think of the `R-intro` folder as our project folder; all files that are
useful for our data analysis project (code, data, other documents),
and all results we generate from these files should be saved within
this folder. This will allow us to more easily keep track of our
work.

## Downloading the data

Download the file that contains all associations with added ontology
from [here](http://www.ebi.ac.uk/gwas/api/search/downloads/alternative).

Copy this file to [data](data) folder in git repository, and rename
this file as `gwas_catalog.tsv`.

See [here](https://www.ebi.ac.uk/gwas/docs/fileheaders) for details on
what is contained in this file.

In summary, give full file structure:

```
R-intro/
├── README.md
├── LICENSE
├── data
│   ├── README.md
│   └── gwas_catalog.tsv
└── analysis
    ├── README.md
    └── demo_gwas_catalog.Rmd
```

## Set working directory

## Installing and using the packages

Explain briefly what packages are, how to access them.

Mention which packages we will use.

## Executing the R code

*Add content for this section.*

## Reading the data into the R environment

The GWAS data set is a large table with 35,077 rows and X columns. It
could conceivably be opened in Excel. To illustrate this, open the
[gwas_catalog_small.xlsx](/data/gwas_catalog_small.xlsx) Excel
spreadsheet, which contains the first 100 rows of the GWAS Catalog
table.

```{r}
plot(cars)
```

## (Another section goes here)

* Add content for another section, as needed.*

## About this document

*Add session info.*